In [10]:
#Author: Alihan UÃ§ar
import pandas as pd

def future_loss_analysis(contract_price, contract_amount, market_price_contract):
    # Calculate initial variables
    free_money = 2 * contract_price
    initial_investment = contract_amount * contract_price
    contract_size_usd = contract_amount * contract_multiplier
    total_size_investment_try = contract_size_usd * market_price_contract
    leverage_rate = total_size_investment_try / initial_investment

    # Create initial dataframe
    data = {'F_USDTRY0423 Contract Price': [contract_price], 
            'Free Money in Account': [free_money], 
            'Contract Amount': [contract_amount], 
            'Initial Investment': [initial_investment], 
            'Total Capital': [free_money + initial_investment], 
            'Contract Size by USD': [contract_size_usd], 
            'Changing Contract Price': [market_price_contract], 
            'Total Size of Investment by TRY': [total_size_investment_try], 
            'Leverage Rate': [leverage_rate]}
    df = pd.DataFrame(data)

    # Calculate data for future prices
    while contract_amount > 0:
        new_price = market_price_contract - 0.05
        new_total_size_investment_try = contract_size_usd * new_price
        free_money -= (total_size_investment_try - new_total_size_investment_try)
        
        # Adjust contract amount if not enough free money
        while free_money < 0:
            contract_amount -= 1
            free_money += contract_price
            contract_size_usd = contract_amount * 1000
            new_total_size_investment_try = contract_size_usd * new_price
        
        # Calculate new investment and leverage rate
        new_investment = contract_amount * contract_price
        new_leverage_rate = leverage_rate
        
        # Create new row for dataframe and append to df
        new_row = pd.DataFrame({'F_USDTRY0423 Contract Price': [contract_price], 
                                'Free Money in Account': [free_money], 
                                'Contract Amount': [contract_amount], 
                                'Initial Investment': [new_investment], 
                                'Total Capital': [free_money + new_investment], 
                                'Contract Size by USD': [contract_size_usd], 
                                'Changing Contract Price': [new_price], 
                                'Total Size of Investment by TRY': [new_total_size_investment_try], 
                                'Leverage Rate': [new_leverage_rate]})
        df = pd.concat([df, new_row], ignore_index=True)
        market_price_contract = new_price
        total_size_investment_try = new_total_size_investment_try

    return df

# Example usage
contract_price = 2665
contract_amount = 4
market_price_contract = 18.9795

# 1 USD/TRY Contract equal 1000 USD size position
contract_multiplier = 1000

# Call the function, save the dataframe as an excel and show the first 5 rows of the dataframe.
df = future_loss_analysis(contract_price, contract_amount, market_price_contract)
df.to_excel('USDTRY_future_investment_risk.xlsx', index=False)
df.head()

,F_USDTRY0423 Contract Price,Free Money in Account,Contract Amount,Initial Investment,Total Capital,Contract Size by USD,Changing Contract Price,Total Size of Investment by TRY,Leverage Rate
0,2665,5330.0,4,10660,15990.0,4000,18.9795,75918.0,7.121764
1,2665,5130.0,4,10660,15790.0,4000,18.9295,75718.0,7.121764
2,2665,4930.0,4,10660,15590.0,4000,18.8795,75518.0,7.121764
3,2665,4730.0,4,10660,15390.0,4000,18.8295,75318.0,7.121764
4,2665,4530.0,4,10660,15190.0,4000,18.7795,75118.0,7.121764